springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
// momo
momo.partnerCode=MOMOLRJZ20181206
momo.accessKey=mTCKt9W3eU1m39TW
momo.secretKey=SetA5RDnLHvt51AULf51DyauxUo3kDU6

momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.redirectUrl=http://127.0.0.1:5500/project-bookeStore-fe-main/payment-result.html
momo.ipnUrl=http://localhost:6060/api/momo/callback
// vietqr
vietqr.bank-id=970422
#vietqr.account-number=1182718591
vietqr.account-number=0375678244
vietqr.account-name=LU NGOC THINH


